import { useState } from 'react'
import { Link } from 'react-router-dom'
import { BarChart3, BriefcaseBusiness, LineChart, Loader2, ShieldCheck } from 'lucide-react'
import { useAuth } from '../context/AuthContext'

const ROLES = [
  {
    key: 'business_leader',
    label: 'Business Leader',
    icon: BriefcaseBusiness,
    blurb: 'Decision-oriented view: what changed, whether it matters, the leading explanation, and what to do next.',
  },
  {
    key: 'data_analyst',
    label: 'Data Analyst',
    icon: LineChart,
    blurb:
      'Everything the leader sees, plus the statistical method, driver tables, the evidence ledger behind every confidence score, and document retrieval.',
  },
]

export default function AuthPage({ mode = 'signin' }) {
  const { signUp, signIn, signInWithGoogle, firebaseConfigured, authMode, notice, describeAuthError } = useAuth()
  const isSignup = mode === 'signup'

  const [form, setForm] = useState({
    email: '',
    password: '',
    displayName: '',
    organisation: '',
    role: 'business_leader',
  })
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState(null)

  const set = (key) => (e) => setForm((f) => ({ ...f, [key]: e.target.value }))

  async function submit(e) {
    e.preventDefault()
    setBusy(true)
    setError(null)
    try {
      if (isSignup) await signUp(form)
      else await signIn(form)
    } catch (err) {
      setError(describeAuthError(err))
    } finally {
      setBusy(false)
    }
  }

  async function google() {
    setBusy(true)
    setError(null)
    try {
      await signInWithGoogle(form.role)
    } catch (err) {
      setError(describeAuthError(err))
    } finally {
      setBusy(false)
    }
  }

  return (
    <div className="grid min-h-screen lg:grid-cols-2">
      {/* pitch panel */}
      <section className="hidden flex-col justify-between p-10 lg:flex" style={{ background: 'var(--surface-1)' }}>
        <div className="flex items-center gap-2">
          <span className="flex h-8 w-8 items-center justify-center rounded-md" style={{ background: 'var(--series-1)' }}>
            <BarChart3 className="h-4 w-4 text-white" aria-hidden />
          </span>
          <span className="text-base font-semibold tracking-tight text-ink">
            BusinessIntelligence<span style={{ color: 'var(--series-1)' }}>.ai</span>
          </span>
        </div>

        <div className="max-w-lg">
          <h1 className="text-3xl font-semibold leading-tight tracking-tight text-ink">
            Business intelligence should not stop at telling you <em>what</em> happened.
          </h1>
          <p className="mt-4 text-base text-ink-secondary">
            It should help you understand why, challenge that explanation, and decide what to do next.
          </p>
          <ol className="mt-8 space-y-4">
            {[
              ['Observe', 'Separate a meaningful change from normal business variation, and find what drove it.'],
              ['Investigate', 'Generate competing explanations and test each against your data and your documents.'],
              ['Contest', 'Actively try to disprove them — timing, consistency, counterexamples, contradictions.'],
              ['Act', 'Turn what survives into evidence-backed recommendations, with the uncertainty intact.'],
            ].map(([title, blurb], i) => (
              <li key={title} className="flex gap-3">
                <span
                  className="tnum flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-semibold text-white"
                  style={{ background: 'var(--series-1)' }}
                >
                  {i + 1}
                </span>
                <div>
                  <div className="text-sm font-semibold text-ink">{title}</div>
                  <p className="text-sm text-ink-secondary">{blurb}</p>
                </div>
              </li>
            ))}
          </ol>
        </div>

        <p className="text-xs text-ink-muted">
          Numbers are computed by a deterministic analysis layer, never generated by a language model.
        </p>
      </section>

      {/* form panel */}
      <section className="flex items-center justify-center p-6 sm:p-10">
        <div className="w-full max-w-md">
          <div className="mb-6 lg:hidden">
            <div className="flex items-center gap-2">
              <span className="flex h-8 w-8 items-center justify-center rounded-md" style={{ background: 'var(--series-1)' }}>
                <BarChart3 className="h-4 w-4 text-white" aria-hidden />
              </span>
              <span className="text-base font-semibold tracking-tight text-ink">
                BusinessIntelligence<span style={{ color: 'var(--series-1)' }}>.ai</span>
              </span>
            </div>
          </div>

          <h2 className="text-xl font-semibold text-ink">{isSignup ? 'Create your account' : 'Sign in'}</h2>
          <p className="mt-1 text-sm text-ink-secondary">
            {isSignup
              ? 'Your data, documents and investigations are private to your account.'
              : 'Welcome back.'}
          </p>

          {notice ? (
            <div
              className="mt-4 flex gap-2 rounded-lg border-l-4 px-3 py-2 text-xs"
              style={{ borderColor: 'var(--status-warning)', background: 'var(--surface-1)' }}
            >
              <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0" style={{ color: 'var(--status-warning)' }} aria-hidden />
              <span className="text-ink-secondary">{notice}</span>
            </div>
          ) : null}

          <form onSubmit={submit} className="mt-6 space-y-4">
            {isSignup ? (
              <fieldset>
                <legend className="label">I am a…</legend>
                <div className="grid gap-2 sm:grid-cols-2">
                  {ROLES.map(({ key, label, icon: Icon, blurb }) => {
                    const selected = form.role === key
                    return (
                      <label
                        key={key}
                        className="card cursor-pointer p-3 transition-shadow hover:shadow-sm"
                        style={selected ? { outline: '2px solid var(--series-1)', outlineOffset: '-1px' } : undefined}
                      >
                        <input
                          type="radio"
                          name="role"
                          value={key}
                          checked={selected}
                          onChange={set('role')}
                          className="sr-only"
                        />
                        <span className="flex items-center gap-2 text-sm font-semibold text-ink">
                          <Icon className="h-4 w-4" style={{ color: selected ? 'var(--series-1)' : 'var(--text-muted)' }} aria-hidden />
                          {label}
                        </span>
                        <span className="mt-1 block text-xs text-ink-secondary">{blurb}</span>
                      </label>
                    )
                  })}
                </div>
              </fieldset>
            ) : null}

            {isSignup ? (
              <div className="grid gap-3 sm:grid-cols-2">
                <div>
                  <label className="label" htmlFor="name">Full name</label>
                  <input id="name" className="field" value={form.displayName} onChange={set('displayName')} autoComplete="name" />
                </div>
                <div>
                  <label className="label" htmlFor="org">Organisation</label>
                  <input id="org" className="field" value={form.organisation} onChange={set('organisation')} autoComplete="organization" />
                </div>
              </div>
            ) : null}

            <div>
              <label className="label" htmlFor="email">Work email</label>
              <input
                id="email"
                type="email"
                required
                className="field"
                value={form.email}
                onChange={set('email')}
                autoComplete="email"
                placeholder="you@company.com"
              />
            </div>

            {firebaseConfigured ? (
              <div>
                <label className="label" htmlFor="password">Password</label>
                <input
                  id="password"
                  type="password"
                  required
                  minLength={6}
                  className="field"
                  value={form.password}
                  onChange={set('password')}
                  autoComplete={isSignup ? 'new-password' : 'current-password'}
                />
              </div>
            ) : (
              <p className="rounded-lg px-3 py-2 text-xs text-ink-secondary" style={{ background: 'var(--surface-1)' }}>
                Firebase is not configured in this build, so the backend&rsquo;s demo login is used: enter an email and
                continue. Add your Firebase keys to <code>frontend/.env</code> to enable real password and Google
                sign-in.
              </p>
            )}

            {error ? (
              <p className="text-sm" role="alert" style={{ color: 'var(--status-critical)' }}>
                {error}
              </p>
            ) : null}

            <button type="submit" className="btn-primary w-full" disabled={busy}>
              {busy ? <Loader2 className="h-4 w-4 animate-spin" aria-hidden /> : null}
              {isSignup ? 'Create account' : 'Sign in'}
            </button>

            {firebaseConfigured ? (
              <button type="button" className="btn-ghost w-full" onClick={google} disabled={busy}>
                Continue with Google
              </button>
            ) : null}
          </form>

          <p className="mt-6 text-center text-sm text-ink-secondary">
            {isSignup ? (
              <>
                Already have an account?{' '}
                <Link to="/signin" className="font-medium" style={{ color: 'var(--series-1)' }}>
                  Sign in
                </Link>
              </>
            ) : (
              <>
                New here?{' '}
                <Link to="/signup" className="font-medium" style={{ color: 'var(--series-1)' }}>
                  Create an account
                </Link>
              </>
            )}
          </p>
          <p className="mt-2 text-center text-[11px] text-ink-muted">Authentication mode: {authMode}</p>
        </div>
      </section>
    </div>
  )
}
